name: lanzoscan
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Utility
  percent_indicator: ^4.2.3
  gal: ^2.3.0
  path: ^1.9.0

  #Icons
  cupertino_icons: ^1.0.2

  # UI Components
  flutter_speed_dial: ^7.0.0
  accordion: ^2.6.0
  flutter_spinkit: ^5.2.1
  rounded_loading_button_plus: ^3.0.1

  # Image Handling
  image_picker: ^1.0.7
  image: ^4.1.3
  widgets_to_image: ^1.0.0

  #Machine Learning
  tflite_flutter: ^0.10.4

  #Firebase Packages
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/models/yolov8n.tflite
