name: lanzoscan
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_speed_dial: ^7.0.0
  image_picker: ^1.0.7
  image: ^4.1.3
  tflite_flutter: ^0.10.4
  accordion: ^2.6.0
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/models/yolov8n.tflite
